apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: helloworld
  annotations:
    github.com/project-slug: lakky123/helloworld
spec:
  type: service
  lifecycle: unknown
  owner: guests
